export const GRID_COLS = 30;
export const GRID_ROWS = 10;

export const SCRAMBLE_DURATION = 800;
export const FLIP_DURATION = 300;
export const STAGGER_DELAY = 25;
export const TOTAL_TRANSITION = (GRID_COLS * GRID_ROWS * STAGGER_DELAY) + SCRAMBLE_DURATION + FLIP_DURATION + 500;

export const CHARSET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.,-!?\'/: ';

export const SCRAMBLE_COLORS = [
  '#00D991'
];
